config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users,controllers: {sessions: 'users/sessions'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "admin/admin#index"

  namespace :admin do
    get "/" => "admin#index"
    get "/home" => "home#index"

    resources :luggages do 
      member do 
        get :pay
        get :print
        get :save_charge
        get :show_charge
      end
    end

  end

end

app/views/admin/a_shared/_btn_form.html.erb
<% label_name ||= "提交"%>

<div class="layui-form-item">
  <label for="L_repass" class="layui-form-label"></label>
  <button class="layui-btn" lay-submit lay-filter=""><%= label_name %></button>
  <%= link_to "返回", params[:back], class: "layui-btn" if params[:back].present? %>
</div>

app/views/admin/a_shared/_btn_search.html.erb
<div class="layui-inline layui-show-xs-block">
  <button class="layui-btn"  lay-submit="" lay-filter="sreach"><i class="layui-icon">&#xe615;</i></button>
  <%= link_to "全部", request.path, class: "layui-btn"%>
</div>

app/views/admin/a_shared/_header.html.erb
<div class="container">
  <div class="logo">
    <%= link_to $settings[:site_name], admin_path%>
  </div>

  <div class="left_open">
    <a><i title="展开左侧栏" class="iconfont">&#xe699;</i></a>
  </div>

  <ul class="layui-nav right" lay-filter="">
    <li class="layui-nav-item">
      <a href="javascript:;"><%= current_user.login_name %></a>
    </li>
    <li class="layui-nav-item">
      <% if current_user.blank? %>
        <%= link_to "登录", new_session_path%>
      <% else %>
        <%= link_to "登出", destroy_user_session_path, method: :delete%>
      <% end %>
    </li>
  </ul>
  
</div>

app/views/admin/a_shared/_left_menu.html.erb
<div class="left-nav">
  <div id="side-nav">
    <ul id="nav">
      
      <li>
        <a href="javascript:;">
          <i class="iconfont left-nav-li" lay-tips="托物单管理">&#xe6b8;</i>
          <cite>托物单管理</cite>
          <i class="iconfont nav_right">&#xe697;</i>
        </a>
        <ul class="sub-menu">
          <li>
            <a onclick="xadmin.add_tab('托物单列表','<%= admin_luggages_path %>')">
              <i class="iconfont">&#xe6a7;</i>
              <cite>托物单列表</cite>
            </a>
          </li>
        </ul>
      </li>

    </ul>
  </div>
</div>