config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users,controllers: {sessions: 'users/sessions'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "admin/admin#index"

  namespace :admin do
    get "/" => "admin#index"
    get "/home" => "home#index"

    resources :luggages do 
      member do 
        get :pay
        get :print
        get :save_charge
        get :show_charge
      end
    end

  end

end

app/models/luggage.rb
class Luggage < ApplicationRecord

  #has_many :items, class_name: "LuggageItem", counter_cache: :items_count

  default_value_for :items_count, 1
  default_value_for :card_type, 1

  default_scope -> {order(id: :desc)}

  #证件类型
  CARD_TYPE = {1 => "身份证", 2 => "驾驶证", 3 => "护照", 4 => "港澳通行证", 5 => "台胞证"}
  #结账状态
  PAY_STATUS = {1 => "未结账", 2 => "已结账"}
  #所有状态
  PAY_STATUS_ALL = PAY_STATUS.merge({3 => "未打印"})
  #状态
  #WORKFLOW_STATUS = {stash: "新增", paid: "已结账", printed: "已打印"}

  before_create do 
    self.index_day = self.store_at.index_day
  end

  def generate_no(gstore_at=false)
    self.store_at = Time.now.to_s if gstore_at
    self.no = "#{Date.current.to_s(:number)}#{(Luggage.last.try(:id).to_i+1).to_s.rjust(4,"0")}"
  end

  #计算收费
  def pay_charge
    current_time = Time.now
    t = current_time - self.store_at
    tm = t/60.0  #分钟
    th = t/3600.0 #小时
    total = case 
    when tm < 135
      pay_charge_1(t)
    when th < 24
      pay_charge_2(tm)
    else
      pay_charge_3(th)
    end
    self.total_charge = total
    self.pick_at = current_time
    self.save
  end

  #第一阶段收费
  def pay_charge_1(t)
    8
  end

  #第二阶段收费：分钟
  def pay_charge_2(tm)
    h = tm.floor  #取整
    s = tm.ceil   #取余
    h += 1 if s > 15
    return [(h-2)*4+8, 25].min
  end

  #第三阶段收费：小时
  def pay_charge_3(th)
    day = t/24   #天数
    tm = (t - 24*day)*60  #剩余分钟
    pay_charge_2(tm) + 25 * day
  end

  #是否可以结账
  def can_pay?
    self.pay_status == 1
  end

  #是否可以编辑
  def can_edit?
    self.pay_status == 1
  end

  #是否可以展示
  def can_show?
    self.pay_status == 1
  end

  def can_show_charge?
    self.pay_status > 1
  end

  def can_print?
    self.pay_status >= 2
  end

end

app/controllers/admin/luggages_controller.rb
module Admin
  class LuggagesController < Admin::HomeController

    before_action :check_auth

    def index
      @q = Luggage.ransack(params[:q])
      @luggages = @q.result.page(params[:page])
    end

    def new
      @luggage.generate_no(true)
    end

    def create
      @luggage = Luggage.new(luggage_params)
      @luggage.save ? flash_msg(:success, "托运【#{@luggage.no}】更新成功") : flash_msg(:error, @luggage.errors.messages)
      redirect_to_back 
    end

    def edit
    end

    def update
      @luggage.assign_attributes(luggage_params)
      @luggage.save ? flash_msg(:success, "托运【#{@luggage.no}】更新成功") : flash_msg(:error, @luggage.errors.messages)
      redirect_to_back
    end

    def pay
      return redirect_to_back unless @luggage.can_pay?
      @luggage.pay_charge
    end

    def save_charge
      @luggage.update(pay_status: 2)
      flash_msg(:success, "已收费")
      redirect_to_back
    end

    def print
      render layout: "admin_print"
    end

    private
    def luggage_params
      params.require(:luggage).permit(:user_name,:card_type, :card_no, :remark,:store_at, :mobile, :store_at, :no, :items_count)
    end

    def luggage_charge_params
      params.require(:luggage).permit(:pick_at, :total_charge)
    end

    #检查变更权限
    def check_auth
      return true if @luggage.blank?
      c = case action_name
      when "edit","update"
        @luggage.can_edit?
      when "pay","save_charge"
        @luggage.can_pay?
      else
        true
      end
      return redirect_to_back unless c
    end

  end
end

app/views/admin/luggages/_form.html.erb
<%= render "js" %>
<div class="layui-fluid">
  <div class="layui-row">
    <%= simple_form_for [:admin, @luggage] do |f|%>

      <table class="layui-table th-tcr table-no-border">
        <tr>
          <th width="15%">姓名：</th>
          <td><%= "暂无 "%></td>

          <th width="15%">身份证号码：</th>
          <td><%= "暂无" %></td>

          <td>
            <%= link_to_void "识别证件", id: "connection", class: "layui-btn" %>
            
          </td>
        </tr>
      </table>

      <%= hidden_field_tag :back, params[:back]%>

      <%= f.input :no, label: "货物托运单号", hint: "货物托运单号为系统自动生成", readonly: true%>
      <%= f.input :store_at, as: :string, label: "存时", readonly: true, hint: "#{'系统自动生成当前时间' if @luggage.new_record? }"%>
      <%= f.input :mobile, label: "手机号码"%>
      <%= f.input :items_count, label: "件数", input_html: {min: 1}%>
      <%= f.input :remark, label: "备注", input_html: {class: "layui-textarea"}%>

      <%= render "admin/a_shared/btn_form", f: f%>
    <% end %>
  </div>
</div>

app/views/admin/luggages/_index_td.html.erb
<td><%= luggage.no %></td>
<td><%= luggage.user_name%></td>
<td><%= Luggage::CARD_TYPE[luggage.card_type]%></td>
<td><%= luggage.store_at.to_s %></td>
<td><%= luggage.items_count%></td>
<td><%= Luggage::PAY_STATUS[luggage.pay_status]%></td>
<td class="td-manage x-admin-sm">
  <%= link_to_icon "修改", edit_admin_luggage_path(luggage)%>
  <%= link_to_icon "查看", admin_luggage_path(luggage), remote: true%>
  <%= link_to_icon "结账", pay_admin_luggage_path(luggage) %>
  <%= link_to_icon "查看金额", admin_luggage_path(luggage), remote: true%>
</td>

app/views/admin/luggages/_pay.html.erb
<div class="layui-col-md12">
  <div class="layui-card">
    <div class="layui-card-header">
      <h1><%= title %></h1>
    </div>

    <div class="layui-card-body ">
      <table class="layui-table th-tcr table-no-border">
        <tbody>

          <tr>
            <th>货物托运单号</th>
            <td><%= @luggage.no%></td>

            <th>件数</th>
            <td><%= @luggage.items_count%></td>
          </tr>

          <tr>
            <th>姓名</th>
            <td><%= @luggage.user_name%></td>
            <th>证件号码：</th>
            <td><%= @luggage.card_no%></td>
          </tr>

          <tr>
            <th>手机号码</th>
            <td colspan="3"><%= @luggage.mobile%></td>
          </tr>

          <tr>
            <th>存时</th>
            <td colspan="3"><%= @luggage.store_at%></td>
          </tr>

          <tr>
            <th>取时</th>
            <td colspan="3">
              <%= @luggage.pick_at %>
              <%= tip_msg("此处时间为扫机枪的时间")%>
            </td>
          </tr>

          <tr>
            <th>保管收费</th>
            <td colspan="3" class="red"><%= number_to_currency @luggage.total_charge %></td>
          </tr>

          <tr>
            <th>备注</th>
            <td colspan="5"><%= @luggage.remark%></td>
          </tr>

          <%= yield(:submit)%>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/admin/luggages/_search.html.erb
<div class="layui-card-body ">
  <%= search_form_for @q, url: admin_luggages_path, class: "layui-form layui-col-space5", method: :get do |f|%>
    <div class="layui-inline layui-show-xs-block">
      <%= f.search_field :no_cont, placeholder: "货物托管编号", class: "layui-input" %>
    </div>

    <div class="layui-inline layui-show-xs-block">
      <%= f.search_field :user_name_cont, placeholder: "姓名", class: "layui-input" %>
    </div>

    <div class="layui-inline layui-show-xs-block">
      <%= f.search_field :store_at_gteq, placeholder: "保管开始时间", class: "layui-input laydate_time" %>
    </div>

    <div class="layui-inline layui-show-xs-block">
      <%= f.label "未结账"%>
      <%= f.radio_button :pay_status_eq, 1%>
      <%= f.label "已结账"%>
      <%= f.radio_button :pay_status_eq, 2%>
    </div>

    <%= render "admin/a_shared/btn_search", f: f%>
  <% end %>
</div>

app/views/admin/luggages/_show.html.erb
<div class="layui-col-md12">
  <div class="layui-card">
    <div class="layui-card-header">
      <table class="layui-table th-tcr">
        <tr>
          <th>证件号码：</th>
          <td><%= @luggage.card_no%></td>

          <th>姓名</th>
          <td><%= @luggage.user_name%></td>

          <th>货物托运单号</th>
          <td><%= @luggage.no%></td>
        </tr>
      </table>
    </div>

    <div class="layui-card-body ">
      <table class="layui-table th-tcr table-no-border">
        <tbody>

          <tr>
            <th>货物托运单号</th>
            <td><%= @luggage.no%></td>

            <th>保管日期</th>
            <td><%= @luggage.store_at%></td>

            <th>公司名称</th>
            <td><%= $settings[:company_name]%></td>
          </tr>

          <tr>
            <th>手机号码</th>
            <td><%= @luggage.mobile%></td>

            <th>件数</th>
            <td><%= @luggage.items_count%></td>

            <th></th>
            <td></td>
          </tr>

          <tr>
            <th>备注</th>
            <td colspan="5"><%= @luggage.remark%></td>
          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/admin/luggages/edit.html.erb
<%= render "form"%>

app/views/admin/luggages/index.html.erb
<%= render "search"%>

<div class="layui-card-header">
  <%= link_to_icon "新增", new_admin_luggage_path%>
</div>

<div class="layui-card-body layui-table-body layui-table-main">
  <table class="layui-table layui-form">
    <thead>
      <tr>
        <th>货物托管编号</th>
        <th>姓名</th>
        <th>类型</th>
        <th>保管开始时间</th>
        <th>件数</th>
        <th>结账状态</th>
        <th>操作</th>
      </tr>
    </thead>

    <tbody>
      <% @luggages.each do |luggage|%>
        <tr id="luggage_<%= luggage.id%>">
          <td><%= luggage.no %></td>
          <td><%= luggage.user_name%></td>
          <td><%= Luggage::CARD_TYPE[luggage.card_type]%></td>
          <td><%= luggage.store_at.to_s %></td>
          <td><%= luggage.items_count%></td>
          <td><%= Luggage::PAY_STATUS[luggage.pay_status]%></td>
          <td class="td-manage x-admin-sm">
            <%= link_to_icon "修改", edit_admin_luggage_path(luggage) if luggage.can_edit? %>
            <%= link_to_icon "查看", admin_luggage_path(luggage), remote: true if luggage.can_show? %>
            <%= link_to_icon "结账", pay_admin_luggage_path(luggage) if luggage.can_pay? %>
            <%= link_to_icon "查看金额", show_charge_admin_luggage_path(luggage), remote: true if luggage.can_show_charge? %>
            <%= link_to_icon "打印", print_admin_luggage_path(luggage), target: "_blank" if luggage.can_print? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @luggages%>

app/views/admin/luggages/new.html.erb
<%= render "form" %>

app/views/admin/luggages/pay.html.erb
<%= content_for :submit do %>
  <tr>
    <td colspan="6" class="tc">
      <%= link_to "确认收费", save_charge_admin_luggage_path(@luggage, back: request.fullpath), class: "layui-btn layui-btn-normal", data: {confirm: "确认收费吗？"}%>
      <%= link_to "取消收费", params[:back], class: "layui-btn"%>
    </td>
  </tr>
<% end %>

<%= render "pay", title: "寄存收费"%>

app/views/admin/luggages/print.html.erb
<div id="print-page">
  <div class="layui-card-body">
    <fieldset class="layui-elem-field">
      <legend class="green"><%= @luggage.no %></legend>
      <div class="layui-field-box">
        <table class="layui-table-show">
          <tr>
            <th>姓名：</th>
            <td><%= @luggage.user_name%></td>
          </tr>

          <tr>
            <th>电话：</th>
            <td><%= @luggage.mobile%></td>
          </tr>

          <tr>
            <th>证件号码：</th>
            <td><%= @luggage.no %></td>
          </tr>

          <tr>
            <th>保管开始时间：</th>
            <td><%= @luggage.store_at%></td>
          </tr>

          <tr>
            <th>件数：</th>
            <td><%= @luggage.items_count%></td>
          </tr>

          <tr>
            <th>公司名称：</th>
            <td><%= $settings[:company_name]%></td>
          </tr>
        </table>
      </div>
    </fieldset>
  </div>


  <div class="layui-card-body">
    <fieldset class="layui-elem-field">
      <legend class="green"><%= @luggage.no %></legend>
      <div class="layui-field-box">
        <table class="layui-table-show">
          <tr>
            <th>姓名：</th>
            <td colspan="5"><%= @luggage.user_name%></td>
          </tr>

          <tr>
            <th>电话：</th>
            <td colspan="5"><%= @luggage.mobile%></td>
          </tr>

          <tr>
            <th>取件日期：</th>
            <td colspan="5"><%= @luggage.pick_at %></td>
          </tr>

          <tr>
            <th>收费标准：</th>
            <td colspan="5">占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试占位测试</td>
          </tr>

          <tr>
            <th>服务时间：</th>
            <td colspan="5">7：30 — 20：30</td>
          </tr>

          <tr>
            <th>公司名称：</th>
            <td colspan="5"><%= $settings[:company_name]%></td>
          </tr>

          <tr>
            <th>监督电话：</th>
            <td>0756-8886733</td>
            <th>服务热线：</th>
            <td>0756-8150128</td>
            <th>客户签字：</th>
            <td></td>
          </tr>
        </table>
      </div>
    </fieldset>
  </div>
</div>


app/views/admin/luggages/show.js.erb
layer_tip("查看【<%= @luggage.no%>】", "<%= j(render 'show')%>", {"area": ["70%", "80%"]})

app/views/admin/luggages/show_charge.js.erb

layer_tip("查看【<%= @luggage.no%>】", "<%= j(render 'pay', title: '查看金额')%>", {"area": ["70%", "80%"]})